import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "./components/Navigation";
import Auth from "./components/Auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className=" flex h-screen w-screen">
          <div className=" bg-zinc-700 h-full w-40 border border-slate-950">
            <Nav/>
          </div>
          <div className="flex flex-col grow">
            <div className="flex justify-between bg-neutral-700 h-20 w-full border border-slate-950 border-l-0">
              <div className="m-7 font-bold text-xl">PLANNER</div>
              <Auth/>
            </div>
            <div className="bg-slate-700 grow">{children}</div>
          </div>
        </div>
        
      </body>
    </html>
  );
}
